### ISSUE TITLE
is this grunt 0.4.0 ready?

### ISSUE THREAD

**Issue by Devric** [tinganho/grunt-dot-compiler#1]

**Comment by tinganho** [comment]
yes it should be. I tested it with the release candidate version.

**Comment by Devric** [comment]
ah, i was using the old grunt-dot-compiler... not the contrib one....

i just the last 30min trying to convert it the grunt api to 0.4.0 lol ...

**Comment by tinganho** [comment]
yes I will soon remove the contrib prefix.
