### ISSUE TITLE
remove dot comments

### ISSUE THREAD

**Issue by Devric** [tinganho/grunt-dot-compiler#2]
dot ignores comments /**/

can you add the following to remove when building the tempalte?
i don't know if this one is the same as grunt-contrib-dot-compiler so i didnt do a pull request

```
     return js.replace(/\/\*.*?\*\//gm,'');
```

**Comment by tinganho** [comment]
Ok it is now published in v-0.3.4 in NPM. Both `//`and `/* */` comments are removed now. Please see my new README. I changed the task to 'dot-compile' now.
