### ISSUE TITLE
unpublish grunt-contrib-dot-compiler

### ISSUE THREAD

**Issue by sindresorhus** [tinganho/grunt-dot-compiler#21]
Please unpublish grunt-contrib-dot-compiler from npm, you already use the non-contrib name, and contrib is reserved for official plugins.

**Comment by sindresorhus** [comment]
@tinganho ping

**Comment by tinganho** [comment]
@sindresorhus It has been unpublished long time ago. https://www.npmjs.org/package/grunt-contrib-dot-compiler

**Comment by sindresorhus** [comment]
But your readme says nothing about it. Would be nice if you could add a note of it being deprecated ;)
